
import java.awt.Color;
import java.sql.Date;
import java.sql.Time;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Calendar;
import java.util.Random;
import javax.swing.JButton;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MatheusBento
 */
public class Game extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
    JogoDaVelha jogo;
    Jogador jogador = new Jogador();
    public Game(Jogador jg1, Jogador jg2) {
        initComponents();
        this.setLocationRelativeTo(null);
        setDefaultCloseOperation(this.DISPOSE_ON_CLOSE);
        jogo = new JogoDaVelha(jg1,jg2);
        mensagens(5);
        sortearJogador();
        
        mensagens(3);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        relatorio = new javax.swing.JTextArea();
        btn13 = new javax.swing.JButton();
        btn23 = new javax.swing.JButton();
        btn12 = new javax.swing.JButton();
        btn33 = new javax.swing.JButton();
        btn22 = new javax.swing.JButton();
        btn32 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btn11 = new javax.swing.JButton();
        btn21 = new javax.swing.JButton();
        btn31 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        relatorio.setEditable(false);
        relatorio.setColumns(20);
        relatorio.setRows(5);
        jScrollPane1.setViewportView(relatorio);

        btn13.setText(" ");
        btn13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn13ActionPerformed(evt);
            }
        });

        btn23.setText(" ");
        btn23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn23ActionPerformed(evt);
            }
        });

        btn12.setText(" ");
        btn12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn12ActionPerformed(evt);
            }
        });

        btn33.setText(" ");
        btn33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn33ActionPerformed(evt);
            }
        });

        btn22.setText(" ");
        btn22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn22ActionPerformed(evt);
            }
        });

        btn32.setText(" ");
        btn32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn32ActionPerformed(evt);
            }
        });

        btn11.setText(" ");
        btn11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn11ActionPerformed(evt);
            }
        });

        btn21.setText(" ");
        btn21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn21ActionPerformed(evt);
            }
        });

        btn31.setText(" ");
        btn31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn31ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn31, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(btn11, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn21, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn31, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn32, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn33, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn22, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn12, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn23, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn13, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn13, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn12, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn23, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn22, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn33, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn32, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void sortearJogador(){
    Random rand = new Random();
        int num = rand.nextInt(1)+1;
        if(num==1){
        jogador = jogo.jogador1;
        }else{
        jogador = jogo.jogador2;
        }
    
    }
    public void mudarPeca(){
            if(jogador==jogo.jogador2){
                jogador=jogo.jogador1;
                mensagens(3);
            }else{
                jogador=jogo.jogador2;
                mensagens(3);
            }
            
    }
    public void botoes(boolean op){
    this.btn11.setEnabled(op);
    this.btn12.setEnabled(op);
    this.btn13.setEnabled(op);
    this.btn21.setEnabled(op);
    this.btn22.setEnabled(op);
    this.btn23.setEnabled(op);
    this.btn31.setEnabled(op);
    this.btn32.setEnabled(op);
    this.btn33.setEnabled(op);
    }
    public void mensagens(int retorno){
        String mensagem = "\n" + dateFormat.format(Calendar.getInstance().getTime())+" - ";
        if(retorno == -1){
               mensagem+= "Já jogaram nessa posição";
        }else if(retorno == 3){
                mensagem+= "Vez do player "+ jogador.getNome();
        
        }else if(retorno == 40){
                mensagem+= "O Jogador  "+ jogador.getNome() + " GANHOU";
        botoes(false);
        }
        else if(retorno == 5){
                mensagem+= "O Jogo começou";
        }
        
        else{
            mensagem+= "Jogada feito com sucesso pelo Jogador " + jogador.getNome() + " utilizando a peça " + jogador.getSimbolo();
        }
        this.relatorio.append(mensagem);
    }
    private void btn11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn11ActionPerformed
        int returno = jogo.Jogar(0, 0, jogador);
        mensagens(returno);
        this.btn11.setText(""+jogo.matrix[0][0].getSimbolo());
        if(jogador==jogo.jogador1 && returno!=-1){
            this.btn11.setBackground(Color.BLACK);  
            this.btn11.setForeground(Color.WHITE);  
            
        }else if(jogador==jogo.jogador2 && returno!=-1){
            this.btn11.setBackground(Color.WHITE);  
            this.btn11.setForeground(Color.BLACK);  
        }
        if(returno!=-1){
        mudarPeca();
        }
// TODO add your handling code here:
    }//GEN-LAST:event_btn11ActionPerformed

    private void btn12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn12ActionPerformed
        int returno = jogo.Jogar(0, 1, jogador);
        mensagens(returno);
        this.btn12.setText(""+jogo.matrix[0][1].getSimbolo());
        if(jogador==jogo.jogador1 && returno!=-1){
            this.btn12.setBackground(Color.BLACK);  
            this.btn12.setForeground(Color.WHITE);  
        }else if(jogador==jogo.jogador2 && returno!=-1){
            this.btn12.setBackground(Color.WHITE);  
            this.btn12.setForeground(Color.BLACK);  
        }
        if(returno!=-1){
        mudarPeca();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btn12ActionPerformed
    
    private void btn13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn13ActionPerformed
        int returno = jogo.Jogar(0, 2, jogador);
        mensagens(returno);
        this.btn13.setText(""+jogo.matrix[0][2].getSimbolo());
        if(jogador==jogo.jogador1 && returno!=-1){
            this.btn13.setBackground(Color.BLACK);  
            this.btn13.setForeground(Color.WHITE); 
        }else if(jogador==jogo.jogador2 && returno!=-1){
            this.btn13.setBackground(Color.WHITE);  
            this.btn13.setForeground(Color.BLACK);  
        }
        if(returno!=-1){
        mudarPeca();
        }
    }//GEN-LAST:event_btn13ActionPerformed

    private void btn21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn21ActionPerformed
        int returno = jogo.Jogar(1, 0, jogador);
        mensagens(returno);  
        this.btn21.setText(""+jogo.matrix[1][0].getSimbolo());
        if(jogador==jogo.jogador1 && returno!=-1){
            this.btn21.setBackground(Color.BLACK);  
            this.btn21.setForeground(Color.WHITE);  
        }else if(jogador==jogo.jogador2 && returno!=-1){
            this.btn21.setBackground(Color.WHITE);  
            this.btn21.setForeground(Color.BLACK); 
        }
        if(returno!=-1){
        mudarPeca();
        }
    }//GEN-LAST:event_btn21ActionPerformed

    private void btn22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn22ActionPerformed
        int returno = jogo.Jogar(1, 1, jogador);
        mensagens(returno);  
        this.btn22.setText(""+jogo.matrix[1][1].getSimbolo());
        if(jogador==jogo.jogador1 && returno!=-1){
            this.btn22.setBackground(Color.BLACK);  
            this.btn22.setForeground(Color.WHITE); 
        }else if(jogador==jogo.jogador2 && returno!=-1){
            this.btn22.setBackground(Color.WHITE);  
            this.btn22.setForeground(Color.BLACK);  
        }
        if(returno!=-1){
        mudarPeca();
        }
    }//GEN-LAST:event_btn22ActionPerformed

    private void btn23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn23ActionPerformed
        int returno = jogo.Jogar(1, 2, jogador);
        mensagens(returno);  
        this.btn23.setText(""+jogo.matrix[1][2].getSimbolo());
        if(jogador==jogo.jogador1 && returno!=-1){
            this.btn23.setBackground(Color.BLACK);  
            this.btn23.setForeground(Color.WHITE);  
        }else if(jogador==jogo.jogador2 && returno!=-1){
            this.btn23.setBackground(Color.WHITE);  
            this.btn23.setForeground(Color.BLACK);  
        }
        if(returno!=-1){
        mudarPeca();
        }
    }//GEN-LAST:event_btn23ActionPerformed

    private void btn31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn31ActionPerformed
        int returno = jogo.Jogar(2, 0, jogador);
        mensagens(returno);
        this.btn31.setText(""+jogo.matrix[2][0].getSimbolo());
        if(jogador==jogo.jogador1 && returno!=-1){
            this.btn31.setBackground(Color.BLACK);  
            this.btn31.setForeground(Color.WHITE);  
        }else if(jogador==jogo.jogador2 && returno!=-1){
            this.btn31.setBackground(Color.WHITE);  
            this.btn31.setForeground(Color.BLACK);  
        }
        if(returno!=-1){
        mudarPeca();
        }
    }//GEN-LAST:event_btn31ActionPerformed

    private void btn32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn32ActionPerformed
        int returno = jogo.Jogar(2, 1, jogador);
        mensagens(returno);    
        this.btn32.setText(""+jogo.matrix[2][1].getSimbolo());
        if(jogador==jogo.jogador1 && returno!=-1){
            this.btn32.setBackground(Color.BLACK);  
            this.btn32.setForeground(Color.WHITE);  
        }else if(jogador==jogo.jogador2 && returno!=-1){
            this.btn32.setBackground(Color.WHITE);  
            this.btn32.setForeground(Color.BLACK);  
        }
        if(returno!=-1){
        mudarPeca();
        }
    }//GEN-LAST:event_btn32ActionPerformed

    private void btn33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn33ActionPerformed
        int returno = jogo.Jogar(2, 2, jogador);
        mensagens(returno);    
        this.btn33.setText(""+jogo.matrix[2][2].getSimbolo());
        if(jogador==jogo.jogador1 && returno!=-1){
            this.btn33.setBackground(Color.BLACK);  
            this.btn33.setForeground(Color.WHITE);  
        }else if(jogador==jogo.jogador2 && returno!=-1){
            this.btn33.setBackground(Color.WHITE);  
            this.btn33.setForeground(Color.BLACK);  
        }
        if(returno!=-1){
        mudarPeca();
        }
    }//GEN-LAST:event_btn33ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Game().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn11;
    private javax.swing.JButton btn12;
    private javax.swing.JButton btn13;
    private javax.swing.JButton btn21;
    private javax.swing.JButton btn22;
    private javax.swing.JButton btn23;
    private javax.swing.JButton btn31;
    private javax.swing.JButton btn32;
    private javax.swing.JButton btn33;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea relatorio;
    // End of variables declaration//GEN-END:variables
}
